name: Deploy HML
on:
  push:
    branches: [develop]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  deploy:
    if: vars.DEPLOY_ENABLED == 'true'
    needs: ci
    uses: ./.github/workflows/release.yml
    with:
      target: hml
    secrets: inherit
